import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { CONFIG } from "../config.js";
const sb=createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s),esc=x=>String(x??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let sessions=[],events=[],selected=null,adminSecret=sessionStorage.getItem("pvp_admin_secret")||"";
const norm=x=>String(x||"").trim().toLowerCase();
function displayType(t){return ({battle_start:"Inicio",session_enable:"Habilitada",capture_enable:"Habilitada",switch:"Cambio",send_out:"Cambio",poke:"Pokémon",damage:"Daño",faint:"KO",one_shot:"One shot",battle_end:"Fin"})[t]||t}
function buildSide(name){const ev=events.filter(e=>[e.trainer,e.target_trainer,e.killer_trainer,e.victim_trainer].some(x=>norm(x)===norm(name)));const names=[];for(const e of ev){for(const [trainer,poke] of [[e.trainer,e.pokemon],[e.killer_trainer,e.killer_pokemon],[e.victim_trainer,e.victim_pokemon],[e.target_trainer,e.target_pokemon]])if(norm(trainer)===norm(name)&&poke&&!names.some(x=>norm(x)===norm(poke)))names.push(poke)}const fainted=new Set(ev.filter(e=>e.event_type==='faint'&&norm(e.victim_trainer)===norm(name)).map(e=>norm(e.victim_pokemon)));let active=null;for(const e of ev.filter(e=>['switch','send_out','poke'].includes(e.event_type)&&norm(e.trainer)===norm(name)).sort((a,b)=>(a.event_number??0)-(b.event_number??0)))active=e.pokemon;const hp=new Map();for(const e of ev.filter(e=>e.event_type==='damage'&&norm(e.target_trainer)===norm(name)))if(e.target_pokemon&&e.hp_after!=null)hp.set(norm(e.target_pokemon),Number(e.hp_after));return {names,fainted,active,hp}}
function sideCards(name){const s=buildSide(name);return s.names.map(p=>{const dead=s.fainted.has(norm(p)),active=norm(s.active)===norm(p),hp=s.hp.get(norm(p));return `<div class="pokemon-live-card ${dead?'fainted':''} ${active?'active':''}"><strong>${esc(p)}</strong>${active?'<span class="active-tag">ACTIVO</span>':''}${dead?'<span class="ko-tag">❌ debilitado</span>':''}${hp!=null&&!dead?`<div class="hpbar"><i style="width:${Math.max(0,Math.min(100,hp))}%"></i></div><small>${hp.toFixed(1)}%</small>`:''}</div>`}).join('')||'<div class="muted">Aún no sacó Pokémon.</div>'}
function timelineLine(e){const t=e.event_timestamp?new Date(e.event_timestamp).toLocaleTimeString('es-BO',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'';let text=displayType(e.event_type);if(['switch','send_out','poke'].includes(e.event_type))text=`${e.trainer||''} sacó a ${e.pokemon||''}`;if(e.event_type==='damage')text=`${e.pokemon||'?'} hizo ${Number(e.damage||0).toFixed(1)}% a ${e.target_pokemon||'?'}`;if(e.event_type==='faint')text=`${e.killer_pokemon||'?'} debilitó a ${e.victim_pokemon||'?'}`;if(e.event_type==='one_shot')text=`💥 ONE SHOT: ${e.killer_pokemon||e.pokemon||'?'} → ${e.victim_pokemon||e.target_pokemon||'?'}`;if(['battle_end','win','end'].includes(e.event_type))text=`Resultado detectado: ${e.raw_payload?.winner||selected?.winner||'—'} ganó`;return `<div class="timeline-row"><time>${esc(t)}</time><span>${esc(text)}</span></div>`}
function render(){const select=$('#sessionSelect');select.innerHTML=sessions.map(s=>`<option value="${s.id}" ${selected?.id===s.id?'selected':''}>${esc(s.tournament_name|| (s.mode==='pvp'?'PVP':'Torneo'))} · ${esc(s.player_a||'?')} vs ${esc(s.player_b||'?')} · ${esc(s.status)}</option>`).join('')||'<option>Sin sesiones</option>';$('#emptyState').hidden=!!selected;$('#livePanel').hidden=!selected;if(!selected)return;$('#battleTitle').textContent=selected.mode==='tournament'?`🏆 ${selected.tournament_name||'Torneo'}`:'⚔️ PVP 1v1';$('#playerA').textContent=selected.player_a||'Jugador A';$('#playerB').textContent=selected.player_b||'Jugador B';const fa=events.filter(e=>e.event_type==='faint'&&norm(e.victim_trainer)===norm(selected.player_b)).length,fb=events.filter(e=>e.event_type==='faint'&&norm(e.victim_trainer)===norm(selected.player_a)).length;$('#scoreA').textContent=fa;$('#scoreB').textContent=fb;$('#teamA').innerHTML=sideCards(selected.player_a);$('#teamB').innerHTML=sideCards(selected.player_b);$('#timeline').innerHTML=events.slice().sort((a,b)=>(a.event_number??999999)-(b.event_number??999999)||new Date(a.created_at)-new Date(b.created_at)).map(timelineLine).join('')||'<div class="muted">Esperando eventos...</div>';const statusText={waiting:'ESPERANDO BATALLA',live:'● EN VIVO',awaiting_confirmation:'RESULTADO DETECTADO',finished:'FINALIZADA',rematch:'REMATCH',cancelled:'CANCELADA'}[selected.status]||selected.status;$('#liveStatus').textContent=statusText;$('#liveStatus').classList.toggle('ended',['finished','cancelled','rematch'].includes(selected.status));$('#adminBox').hidden=!adminSecret}
async function load(){const {data:s,error}=await sb.from('battle_sessions').select('*').in('status',['waiting','live','awaiting_confirmation','finished','rematch']).order('updated_at',{ascending:false}).limit(30);if(error){console.error(error);return}sessions=s||[];const wanted=new URLSearchParams(location.search).get('session');selected=sessions.find(x=>x.id===(wanted||$('#sessionSelect')?.value))||sessions[0]||null;if(selected){const {data:e}=await sb.from('battle_events').select('*').eq('battle_session_id',selected.id).order('event_number',{ascending:true});events=e||[]}else events=[];render()}
$('#sessionSelect').onchange=async()=>{selected=sessions.find(x=>x.id===$('#sessionSelect').value)||null;if(selected){const {data}=await sb.from('battle_events').select('*').eq('battle_session_id',selected.id).order('event_number');events=data||[]}render()};
$('#adminToggle').onclick=()=>{if(adminSecret){adminSecret='';sessionStorage.removeItem('pvp_admin_secret');render();return}const x=prompt('Secreto de administración PVP:');if(x){adminSecret=x;sessionStorage.setItem('pvp_admin_secret',x);render()}};
async function adminAction(action){if(!selected||!adminSecret)return;const r=await fetch(`${CONFIG.SUPABASE_URL}/functions/v1/pvp-admin`,{method:'POST',headers:{'Content-Type':'application/json','x-pvp-admin-secret':adminSecret},body:JSON.stringify({action,sessionId:selected.id})});const x=await r.json();$('#adminResult').textContent=x.ok?(x.note||'Listo.'):(x.error||'Error');if(r.status===401){adminSecret='';sessionStorage.removeItem('pvp_admin_secret')}await load()}
$('#finishBattle').onclick=()=>adminAction('finish');$('#rematchBattle').onclick=()=>confirm('¿Preparar rematch de esta sesión?')&&adminAction('rematch');$('#cancelBattle').onclick=()=>confirm('¿Cancelar esta sesión?')&&adminAction('cancel');
sb.channel('pvp-live-sessions').on('postgres_changes',{event:'*',schema:'public',table:'battle_sessions'},load).subscribe();sb.channel('pvp-live-events').on('postgres_changes',{event:'*',schema:'public',table:'battle_events'},load).subscribe();await load();
