import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { CONFIG } from "../config.js";
const sb=createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=x=>String(x??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tournaments=[],rosters=[],revealed=[],sessions=[],events=[],teamToken=sessionStorage.getItem('team_roster_token')||'',teamAccount=null,myRoster=null,myPokemon=[];
const norm=x=>String(x||'').trim().toLowerCase();
const modal=(open=true)=>$('#pokemonModal').classList.toggle('open',open);$$('[data-close]').forEach(x=>x.onclick=()=>modal(false));
async function edgeTeam(body,auth=true){const r=await fetch(`${CONFIG.SUPABASE_URL}/functions/v1/team-roster`,{method:'POST',headers:{'Content-Type':'application/json',...(auth&&teamToken?{Authorization:`Bearer ${teamToken}`}:{})},body:JSON.stringify(body)});return {status:r.status,...await r.json()}}
async function loadBase(){const [t,r,p,s,e]=await Promise.all([sb.from('tournaments').select('id,name,status,created_at').order('created_at',{ascending:false}),sb.from('tournament_rosters').select('*'),sb.from('tournament_pokemon').select('*').eq('revealed',true),sb.from('battle_sessions').select('*').eq('status','finished'),sb.from('battle_events').select('*').order('event_number')]);tournaments=t.data||[];rosters=r.data||[];revealed=p.data||[];sessions=s.data||[];events=e.data||[];const select=$('#tournamentSelect');const cur=select.value;select.innerHTML=tournaments.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')||'<option>Sin torneos</option>';if(cur&&tournaments.some(x=>x.id===cur))select.value=cur;await loadMine();render()}
async function loadMine(){myRoster=null;myPokemon=[];if(!teamToken||!$('#tournamentSelect').value)return;const x=await edgeTeam({action:'get',tournamentId:$('#tournamentSelect').value});if(!x.ok){if(x.status===401){teamToken='';teamAccount=null;sessionStorage.removeItem('team_roster_token')}return}myRoster=x.roster;myPokemon=x.pokemon||[];if(myRoster){$('#trainerName').value=myRoster.trainer_name||'';$('#teamPokemon').value=myPokemon.map(x=>x.pokemon_name).join('\n')}}
function usedPokemonForTrainer(tid,trainer){const ss=sessions.filter(s=>s.tournament_id===tid&&(norm(s.player_a)===norm(trainer)||norm(s.player_b)===norm(trainer)));const ids=new Set(ss.map(s=>s.id));const names=[];for(const e of events.filter(e=>ids.has(e.battle_session_id))){for(const [tr,p] of [[e.trainer,e.pokemon],[e.killer_trainer,e.killer_pokemon],[e.victim_trainer,e.victim_pokemon],[e.target_trainer,e.target_pokemon]])if(norm(tr)===norm(trainer)&&p&&!names.some(x=>norm(x)===norm(p)))names.push(p)}return names}
function playerStats(tid,trainer){const ss=sessions.filter(s=>s.tournament_id===tid&&(norm(s.player_a)===norm(trainer)||norm(s.player_b)===norm(trainer)));let wins=0,losses=0,kf=0,ka=0,best=null,worst=null;const use=new Map();for(const s of ss){const won=norm(s.winner)===norm(trainer);if(won)wins++;else if(s.winner)losses++;const ev=events.filter(e=>e.battle_session_id===s.id);const plus=ev.filter(e=>e.event_type==='faint'&&norm(e.killer_trainer)===norm(trainer)).length,minus=ev.filter(e=>e.event_type==='faint'&&norm(e.victim_trainer)===norm(trainer)).length;kf+=plus;ka+=minus;const diff=plus-minus,opp=norm(s.player_a)===norm(trainer)?s.player_b:s.player_a,item={opp,diff,score:`${plus}-${minus}`};if(!best||diff>best.diff)best=item;if(!worst||diff<worst.diff)worst=item;const perSession=new Set();for(const e of ev){for(const [tr,p] of [[e.trainer,e.pokemon],[e.killer_trainer,e.killer_pokemon],[e.victim_trainer,e.victim_pokemon],[e.target_trainer,e.target_pokemon]])if(norm(tr)===norm(trainer)&&p)perSession.add(p)}for(const p of perSession)use.set(p,(use.get(p)||0)+1)}return {wins,losses,kf,ka,best,worst,use:[...use].sort((a,b)=>b[1]-a[1])}}
function pokemonStats(tid,trainer,pokemon){const ss=sessions.filter(s=>s.tournament_id===tid&&(norm(s.player_a)===norm(trainer)||norm(s.player_b)===norm(trainer)));const rows=[];let damage=0,kos=0,one=0,fainted=0,wins=0,losses=0,used=0;const victims=[];for(const s of ss){const ev=events.filter(e=>e.battle_session_id===s.id);const wasUsed=ev.some(e=>[[e.trainer,e.pokemon],[e.killer_trainer,e.killer_pokemon],[e.victim_trainer,e.victim_pokemon],[e.target_trainer,e.target_pokemon]].some(([tr,p])=>norm(tr)===norm(trainer)&&norm(p)===norm(pokemon)));if(!wasUsed)continue;used++;if(norm(s.winner)===norm(trainer))wins++;else if(s.winner)losses++;let d=0,k=0,o=0,f=0;for(const e of ev){if(e.event_type==='damage'&&norm(e.trainer)===norm(trainer)&&norm(e.pokemon)===norm(pokemon)){d+=Number(e.damage||0);damage+=Number(e.damage||0)}if(e.event_type==='faint'&&norm(e.killer_trainer)===norm(trainer)&&norm(e.killer_pokemon)===norm(pokemon)){k++;kos++}if(e.event_type==='faint'&&norm(e.victim_trainer)===norm(trainer)&&norm(e.victim_pokemon)===norm(pokemon)){f++;fainted++}if(e.event_type==='one_shot'&&norm(e.killer_trainer||e.trainer)===norm(trainer)&&norm(e.killer_pokemon||e.pokemon)===norm(pokemon)){o++;one++;const v=e.victim_pokemon||e.target_pokemon;if(v)victims.push(v)}}rows.push({session:s,damage:d,kos:k,one:o,fainted:f})}return {damage,kos,one,fainted,wins,losses,used,victims,rows,avgDamage:used?damage/used:0,avgKos:used?kos/used:0,avgOne:used?one/used:0,avgFainted:used?fainted/used:0}}
function render(){const tid=$('#tournamentSelect').value;$('#myTeamAuth').textContent=teamToken?`Sesión privada activa${teamAccount?.username?` · ${teamAccount.username}`:''}`:'No autenticado. Pulsa “Iniciar sesión de equipo”.';$('#teamEditor').hidden=!teamToken;const rs=rosters.filter(r=>r.tournament_id===tid);$('#rosterGrid').innerHTML=rs.map(r=>{const mine=myRoster?.id===r.id;const pub=revealed.filter(p=>p.roster_id===r.id).map(p=>p.pokemon_name);const all=mine?myPokemon.map(p=>p.pokemon_name):pub;const total=mine?all.length:Math.max(Number(r.roster_size||0),all.length);const slots=[...all.map(p=>`<button class="pokemon-slot revealed" data-pokemon="${esc(p)}" data-trainer="${esc(r.trainer_name)}">${esc(p)}</button>`),...Array.from({length:Math.max(0,total-all.length)},()=>'<div class="pokemon-slot hidden-pokemon">????</div>')].join('');return `<article class="card trainer-roster"><h3>${esc(r.trainer_name)}${mine?' · Tú':''}</h3><div class="pokemon-slot-grid">${slots||'<span class="muted">Sin Pokémon registrados.</span>'}</div></article>`}).join('')||'<div class="muted">Todavía no hay equipos registrados para este torneo.</div>';
$('#playerStats').innerHTML=rs.map(r=>{const s=playerStats(tid,r.trainer_name);return `<article class="card"><h3>${esc(r.trainer_name)}</h3><div class="stat-grid"><span>Victorias <b>${s.wins}</b></span><span>Derrotas <b>${s.losses}</b></span><span>KO+ <b>${s.kf}</b></span><span>KO− <b>${s.ka}</b></span></div><p><b>Mejor partida:</b> ${s.best?`${esc(s.best.opp)} · ${s.best.score} (${s.best.diff>=0?'+':''}${s.best.diff})`:'—'}</p><p><b>Peor partida:</b> ${s.worst?`${esc(s.worst.opp)} · ${s.worst.score} (${s.worst.diff>=0?'+':''}${s.worst.diff})`:'—'}</p><div><b>Pokémon más usados:</b> ${s.use.length?s.use.map(([p,n],i)=>`${i+1}. ${esc(p)} (${n})`).join(' · '):'—'}</div></article>`}).join('')||'<div class="muted">Sin estadísticas todavía.</div>';
$$('[data-pokemon]').forEach(b=>b.onclick=()=>showPokemon(b.dataset.trainer,b.dataset.pokemon))}
function showPokemon(trainer,pokemon){const tid=$('#tournamentSelect').value,s=pokemonStats(tid,trainer,pokemon);$('#pokemonModalTitle').textContent=`${pokemon} · ${trainer}`;$('#pokemonModalBody').innerHTML=`<div class="stat-grid"><span>Partidas usado <b>${s.used}</b></span><span>Daño total <b>${s.damage.toFixed(1)}%</b></span><span>KO <b>${s.kos}</b></span><span>One-shots <b>${s.one}</b></span><span>Veces debilitado <b>${s.fainted}</b></span><span>Victorias <b>${s.wins}</b></span><span>Derrotas <b>${s.losses}</b></span></div><h3>Promedios del torneo</h3><div class="stat-grid"><span>Daño/partida <b>${s.avgDamage.toFixed(1)}%</b></span><span>KO/partida <b>${s.avgKos.toFixed(2)}</b></span><span>One-shot/partida <b>${s.avgOne.toFixed(2)}</b></span><span>Debilitado/partida <b>${s.avgFainted.toFixed(2)}</b></span></div><h3>One-shots realizados</h3><p>${s.victims.length?s.victims.map(esc).join(', '):'Ninguno'}</p><h3>Por pelea</h3>${s.rows.map(r=>`<div class="card compact">vs ${esc(norm(r.session.player_a)===norm(trainer)?r.session.player_b:r.session.player_a)} · daño ${r.damage.toFixed(1)}% · KO ${r.kos} · one-shot ${r.one} · debilitado ${r.fainted}</div>`).join('')||'<p class="muted">Sin partidas.</p>'}`;modal(true)}
$('#tournamentSelect').onchange=async()=>{await loadMine();render()};
$('#teamLogin').onclick=async()=>{if(teamToken){teamToken='';teamAccount=null;sessionStorage.removeItem('team_roster_token');await loadMine();render();return}const username=prompt('Usuario de Apueston:');if(!username)return;const password=prompt('Contraseña:');if(password===null)return;const x=await edgeTeam({action:'login',username,password},false);if(!x.ok)return alert(x.error||'No se pudo iniciar sesión.');teamToken=x.token;teamAccount=x.account;sessionStorage.setItem('team_roster_token',teamToken);await loadMine();render()};
$('#saveTeam').onclick=async()=>{if(!teamToken)return;const names=$('#teamPokemon').value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);const x=await edgeTeam({action:'save',tournamentId:$('#tournamentSelect').value,trainerName:$('#trainerName').value.trim()||teamAccount?.username,pokemon:names});if(!x.ok)return alert(x.error||'No se pudo guardar.');alert(`Equipo guardado: ${x.count} Pokémon.`);await loadBase()};
sb.channel('teams-rosters').on('postgres_changes',{event:'*',schema:'public',table:'tournament_rosters'},loadBase).subscribe();sb.channel('teams-reveals').on('postgres_changes',{event:'*',schema:'public',table:'tournament_pokemon'},loadBase).subscribe();sb.channel('teams-sessions').on('postgres_changes',{event:'*',schema:'public',table:'battle_sessions'},loadBase).subscribe();sb.channel('teams-events').on('postgres_changes',{event:'*',schema:'public',table:'battle_events'},loadBase).subscribe();await loadBase();
